/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -N -i libsocialweb-qt/swclientdbustypes.h -a ../interfaces/collections_adaptor.h:../interfaces/collections_adaptor.cpp ../interfaces/collections.xml
 *
 * qdbusxml2cpp is Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "../interfaces/collections_adaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class CollectionsAdaptor
 */

CollectionsAdaptor::CollectionsAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

CollectionsAdaptor::~CollectionsAdaptor()
{
    // destructor
}

bool CollectionsAdaptor::Create(const QString &collection_name, uint supported_types, const QString &collection_parent, SwParams extra_parameters)
{
    // handle method call com.meego.ux.sharing.service.collections.Create
    bool success;
    QMetaObject::invokeMethod(parent(), "Create", Q_RETURN_ARG(bool, success), Q_ARG(QString, collection_name), Q_ARG(uint, supported_types), Q_ARG(QString, collection_parent), Q_ARG(SwParams, extra_parameters));
    return success;
}

bool CollectionsAdaptor::GetDetails(const QString &collection_id)
{
    // handle method call com.meego.ux.sharing.service.collections.GetDetails
    bool success;
    QMetaObject::invokeMethod(parent(), "GetDetails", Q_RETURN_ARG(bool, success), Q_ARG(QString, collection_id));
    return success;
}

bool CollectionsAdaptor::GetList()
{
    // handle method call com.meego.ux.sharing.service.collections.GetList
    bool success;
    QMetaObject::invokeMethod(parent(), "GetList", Q_RETURN_ARG(bool, success));
    return success;
}

bool CollectionsAdaptor::GetSupportsCollections()
{
    // handle method call com.meego.ux.sharing.service.collections.GetSupportsCollections
    bool SupportsCollections;
    QMetaObject::invokeMethod(parent(), "GetSupportsCollections", Q_RETURN_ARG(bool, SupportsCollections));
    return SupportsCollections;
}

